### ISSUE TITLE
Different replacements for same keyword

### ISSUE THREAD

**Issue by nickdrozd** [aroberge/experimental#3]
(You may already have thought of this, but it just occurred to me and I figured I would open an issue.)

The source transformation approach you use here has the downside that it links keywords that might otherwise be separated. Consider the keyword `in` in Python. This is used to check for membership in iterables and also as part of `for` expressions. But I *think* that these two uses don't have anything to do with each other. An expression like `for x in s: f(x)` is parsed into an AST object with `target`, `iter`, and `body` fields (and `orelse`, but nobody uses that), and at that point the `in` helper keyword is gone.

Now, suppose you wanted to use `dans` as the helper for `pour`, but `appartient` to check for membership:

```
pour nombre dans intervalle(100):
    si nombre appartient premiers:
        imprime(nombre)
```

I don't think that would be possible here. Is there any way around it?

**Comment by aroberge** [comment]
The simple approach I use for keyword replacements would allow one to do this: all that is needed is an extra entry in the dictionnary.  I have done that in the `nobreak` keyword example. https://github.com/aroberge/experimental/blob/master/experimental/transformers/nobreak_keyword.py

The downside of this simple-minded approach is that the additional keyword can be used anywhere the other can; so, using your example, the following would become valid.

```
pour nombre appartient intervalle(100):
    si nombre dans premiers:
        imprime(nombre)
```
which defeats the purpose of having additional keywords.

There would be a quick-and-easy way around that by first parsing the code and ensuring that, if `appartient` appears, it would only do so where a condition would normally be used. Thus, for example, one could flag a syntax error if `pour` would appear on the same line as `appartient`. To make this truly robust, one would possibly have to write a full parser as a replacement of Python's one.

**Comment by nickdrozd** [comment]
Right, the dicts go `{new_keyword: old_keyword}`, rather than the other way around. I've been thinking about keywords a lot recently, and I got mixed up :)
